### ISSUE TITLE
Please put whith the .json whith pt-BR Language

### ISSUE THREAD

**Issue by paulo-correia** [rudwolf/base-wp-repo#1]
Hi Rudolf,
I've been in novatec CT, in the WordPress meetup with composer and there you showed how to put the WP with pt-BR language.
Can you put it here?

**Comment by rudwolf** [comment]
Yes, it's easy, in fact you just have to switch to the other branch: 
https://github.com/rudwolf/base-wp-repo/tree/language_version/pt_BR

And then pull from it, the portuguese language will be there
